name = "ai-workflow-platform"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
output_dir = "out"

[env.production]
name = "ai-workflow-platform"

[env.staging]
name = "ai-workflow-platform-staging"

# 环境变量配置
[vars]
NODE_ENV = "production"

# 路由配置
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# 缓存配置
[headers]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
